# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: build
      steps:
      - task: NodeTool@0
        displayName: 'install: node.js'
        inputs:
          versionSpec: '14.x'
      - task: Bash@3
        displayName: 'npm install and build'
        inputs:
          targetType: 'inline'
          script: |
            cd '$(Build.SourcesDirectory)'
            npm install
            npm run build
      # Code security scan
      # - task: ArchiveFiles@2
      #   displayName: 'Archive files'
      #   inputs:
      #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      #     includeRootFolder: false
      #     archiveType: zip
      #     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      #     replaceExistingArchive: true

      - publish: '$(Build.SourcesDirectory)/build'
        artifact: web-cms
        displayName: 'artifacts: upload web-cms'

  - template: deploy.yml
    parameters:
      dependsOn: Build
      environmentName: ${{ variables['Build.SourceBranchName'] }}
      deployBranch: ${{ variables['Build.SourceBranchName'] }}

  - template: security.yml
    parameters:
      deployBranch: ${{ variables['Build.SourceBranchName'] }}
      environmentName: ${{ variables['Build.SourceBranchName'] }}

  - template: snyk.yml
    parameters:
      deployBranch: ${{ variables['Build.SourceBranchName'] }}
      environmentName: ${{ variables['Build.SourceBranchName'] }}
