parameters:
  - name: deployBranch
    type: string
  - name: environmentName
    type: string

stages:
  - stage: ${{ parameters.environmentName }}_security
    jobs:
      - deployment: security_scan_${{ parameters.environmentName}}
        pool:
          vmImage: 'windows-latest'
        environment: "alakarte-${{ parameters.environmentName}}-cloud"
        strategy:
          runOnce:
            deploy:
              steps:
                # For scanning issues in project and org
                # - task: ADOSecurityScanner@1
                #   inputs:
                #     ADOConnectionName: 'ADO Security Service Connection'
                #     OrgName: '$(System.CollectionUri)'
                #     ProjectNames: '$(System.TeamProject)'
                #     ScanFilter: 'Org_Project_User'
                #     EnableOMSLogging: true
                # For scanning issues in build
                - task: ADOSecurityScanner@1
                  inputs:
                    ADOConnectionName: 'ADO Security Service Connection'
                    OrgName: '$(System.CollectionUri)'
                    ProjectNames: '$(System.TeamProject)'
                    ScanFilter: 'BuildReleaseSvcConnAgentPoolVarGroupUser'
                    BuildNames: 'cms'
                    ReleaseNames: 'r1'
                    ServiceConnectionNames: 'ADO Security Connection'
                    EnableOMSLogging: true
