parameters:
  - name: deployBranch
    type: string
  - name: environmentName
    type: string

stages:
  - stage: ${{ parameters.environmentName }}_code_scan
    jobs:
      - deployment: snyk_scan_${{ parameters.environmentName}}
        pool:
          vmImage: 'ubuntu-latest'
        environment: "alakarte-${{ parameters.environmentName}}-cloud"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: web-cms
                  displayName: 'artifacts: download web-cms'
                - task: SnykSecurityScan@1
                  inputs:
                    serviceConnectionEndpoint: 'Snyk'
                    testType: 'app'
                    monitorWhen: 'always'
                    failOnIssues: true
                    projectName: 'alakarte-cms'